7/3-wednesday-27/spacestation/config/routes.rb
Rails.application.routes.draw do
  resources :stations do
    resources :crews
  end
  root controller: :stations, action: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

7/3-wednesday-27/spacestation/app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :station
end

7/3-wednesday-27/spacestation/app/models/station.rb
class Station < ApplicationRecord
  has_many :crews
end

7/3-wednesday-27/spacestation/app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: [:show, :edit, :update, :destroy]

  # GET /crews
  def index
    @crews = Crew.all
  end

  # GET /crews/1
  def show
  end

  # GET /crews/new
  def new
    @station = Station.find(params[:station_id])
    @crew = @station.crews.build
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  def create
    @station = Station.find(params[:station_id])

    @crew = @station.crews.build(crew_params)

    if @crew.save
      redirect_to [@station, @crew], notice: 'Crew was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /crews/1
  def update
    if @crew.update(crew_params)
      redirect_to @crew, notice: 'Crew was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /crews/1
  def destroy
    @crew.destroy
    redirect_to crews_url, notice: 'Crew was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crew_params
      params.require(:crew).permit(:name, :country_code, :job_title, :station_id, :launch_at)
    end
end

7/3-wednesday-27/spacestation/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  def index
    @stations = Station.all
  end

  # GET /stations/1
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  def create
    @station = Station.new(station_params)

    if @station.save
      redirect_to @station, notice: 'Station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stations/1
  def update
    if @station.update(station_params)
      redirect_to @station, notice: 'Station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stations/1
  def destroy
    @station.destroy
    redirect_to stations_url, notice: 'Station was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def station_params
      params.require(:station).permit(:name, :crew_count, :peripasis, :aposis, :max_fuel, :current_fuel)
    end
end

7/3-wednesday-27/spacestation/app/helpers/crews_helper.rb
module CrewsHelper
end

7/3-wednesday-27/spacestation/app/helpers/stations_helper.rb
module StationsHelper
end

7/3-wednesday-27/spacestation/app/views/crews/_form.html.erb
<%= form_for([@station, @crew]) do |f| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :country_code %>
    <%= f.text_field :country_code %>
  </div>

  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>

  <div class="field">
    <%= f.label :station_id %>
    <%= f.text_field :station_id %>
  </div>

  <div class="field">
    <%= f.label :launch_at %>
    <%= f.datetime_select :launch_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

7/3-wednesday-27/spacestation/app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

7/3-wednesday-27/spacestation/app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country code</th>
      <th>Job title</th>
      <th>Station</th>
      <th>Launch at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= crew.country_code %></td>
        <td><%= crew.job_title %></td>
        <td><%= crew.station %></td>
        <td><%= crew.launch_at %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

7/3-wednesday-27/spacestation/app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', station_crews_path(@station) %>

7/3-wednesday-27/spacestation/app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @crew.country_code %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @crew.job_title %>
</p>

<p>
  <strong>Station:</strong>
  <%= @crew.station&.name %>
</p>

<p>
  <strong>Launch at:</strong>
  <%= @crew.launch_at %>
</p>

<%= link_to 'Edit', edit_station_crew_path(@crew.station_id, @crew) %> |
<%= link_to 'Back', station_crews_path(@crew.station_id) %>

7/3-wednesday-27/spacestation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacestation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

7/3-wednesday-27/spacestation/app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :crew_count %>
    <%= f.number_field :crew_count %>
  </div>

  <div class="field">
    <%= f.label :peripasis %>
    <%= f.text_field :peripasis %>
  </div>

  <div class="field">
    <%= f.label :aposis %>
    <%= f.text_field :aposis %>
  </div>

  <div class="field">
    <%= f.label :max_fuel %>
    <%= f.text_field :max_fuel %>
  </div>

  <div class="field">
    <%= f.label :current_fuel %>
    <%= f.text_field :current_fuel %>
  </div>

  <div class="field">
    <%= f.label :country_code %>
    <%= f.text_field :country_code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

7/3-wednesday-27/spacestation/app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

7/3-wednesday-27/spacestation/app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Crew count</th>
      <th>Peripasis</th>
      <th>Aposis</th>
      <th>Max fuel</th>
      <th>Current fuel</th>
      <th>Country code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.crew_count %></td>
        <td><%= station.peripasis %></td>
        <td><%= station.aposis %></td>
        <td><%= station.max_fuel %></td>
        <td><%= station.current_fuel %></td>
        <td><%= station.country_code %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

7/3-wednesday-27/spacestation/app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

7/3-wednesday-27/spacestation/app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Crew count:</strong>
  <%= @station.crew_count %>
</p>

<p>
  <strong>Peripasis:</strong>
  <%= @station.peripasis %>
</p>

<p>
  <strong>Aposis:</strong>
  <%= @station.aposis %>
</p>

<p>
  <strong>Max fuel:</strong>
  <%= @station.max_fuel %>
</p>

<p>
  <strong>Current fuel:</strong>
  <%= @station.current_fuel %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @station.country_code %>
</p>


<h1>Crew</h1>
<ul>
  <% @station.crews.each do |crew| %>
    <li>
      <%= link_to crew.name, station_crew_path(@station, crew) %>
      <small>
        <%= crew.job_title %>
        <i>
          <%= time_ago_in_words crew.launch_at %> ago
        </i>
      </small>
    </li>
  <% end %>
</ul>











<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>