7/2-tuesday-26/tour/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  # get 'bookings/index', controller: "bookings", action: "index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # get "/", controller: "welcome", action: "homepage"

  root controller: "welcome", action: "homepage"

  # get "/bookings", controller: "bookings", action: "index", as: "bookings"
  # get "/bookings/new", controller: "bookings", action: "new", as: "bookings_new"
  # get "/bookings/:id/edit", controller: "bookings", action: "edit", as: "edit_booking"
  # post "/bookings", controller: "bookings", action: "create"
  # patch "/bookings/:id", controller: "bookings", action: "update"
  # delete "/bookings/:id", controller: "bookings", action: "destroy"

  resources :bookings
  resources :customers
end

7/2-tuesday-26/tour/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :agent, class_name: "User", optional: true
  validates :customer_name, presence: true
  # def bob
  #   "wehadababyitsaboy"
  # end
  #
  # def bob=(a_value)
  #   self.destination += a_value
  # end

  # def customer_name
  #   read_attribute(:customer_name)
  # end
  #
  # def customer_name=(new_value)
  #   write_attribute(:customer_name, new_value)
  # end
end

7/2-tuesday-26/tour/app/models/user.rb
# require "bcrypt"

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  def password
    # @password = @password || BCrypt::Password.new(password_digest)
    @password ||= BCrypt::Password.new(password_digest)
  end

  def password=(plaintext_password)
    encrypted_password = BCrypt::Password.create(plaintext_password)
    self.password_digest = encrypted_password
  end
end

7/2-tuesday-26/tour/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find_by(id: session[:current_user_id])
    end
  end
end

7/2-tuesday-26/tour/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authorize!, except: [:index]

  def index
    @bookings = Booking.all

    # render "index"
  end

  def new
    @booking = Booking.new
    render "new" # If your view name matches your action name it will be looked up by default.
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.agent = current_user
    if @booking.save
      redirect_to bookings_path, flash: { success: "Booking Created successfully" }
    else
      flash[:error] = "Booking could not be saved!"

      render "new"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to "/bookings"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to "/bookings"
  end

  private def booking_params
    params.require("booking").permit(
      "customer_name",
      "destination",
      "bob",
      "start_at",
      "end_at"
    )
  end

  private def authorize!
    if !current_user
      session[:error] = "Go Away"
      redirect_to new_sessions_path
    end
  end
end

7/2-tuesday-26/tour/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      session[:current_user_id] = @user.id
      redirect_to bookings_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to new_sessions_path
  end
end

7/2-tuesday-26/tour/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.email = user_params[:email]
    @user.nickname = user_params[:nickname]
    @user.password = user_params[:password]
    @user.password_confirmation = user_params[:password_confirmation]

    if @user.save
      # Do the actual login thing?
      redirect_to bookings_path
    else
      render "new"
    end
  end

  private def user_params
    params.require(:user).permit(
      :email,
      :nickname,
      :password,
      :password_confirmation
    )
  end
end

7/2-tuesday-26/tour/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
    render "homepage"
  end
end

7/2-tuesday-26/tour/app/helpers/bookings_helper.rb
module BookingsHelper
end

7/2-tuesday-26/tour/app/helpers/sessions_helper.rb
module SessionsHelper
end

7/2-tuesday-26/tour/app/helpers/users_helper.rb
module UsersHelper
end

7/2-tuesday-26/tour/app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>

  <% @booking.errors.full_messages.each do |error| %>
    <p class="field_with_errors"><%= error %></p>
  <% end %>


  <%= f.label :customer_name %>
  <%= f.text_field :customer_name %>

  <%= f.label :destination %>
  <%= f.text_field :destination %>

  <%# f.label :bob   %>
  <%# f.text_field :bob  %>

  <%= f.label :start_at %>
  <%= f.date_field :start_at %>

  <%= f.label :end_at %>
  <%= f.date_field :end_at %>

  <%= f.submit %>
<% end %>

7/2-tuesday-26/tour/app/views/bookings/edit.html.erb
<h1>Editing <%= @booking.customer_name %>'s trip to <%= @booking.destination %></h1>

<%# form_tag "/bookings/#{@booking.id}", method: "patch" do %>
  <%# label_tag "booking[customer_name]", "Customer" %>
  <%# text_field_tag "booking[customer_name]", @booking.customer_name  %>

  <%# label_tag "booking[destination]", "Destination" %>
  <%# text_field_tag "booking[destination]", @booking.destination  %>

  <%# label_tag "booking[start_at]", "Start At" %>
  <%# date_field_tag "booking[start_at]", @booking.start_at&.to_date %>

  <%# label_tag "booking[end_at]", "End At" %>
  <%# date_field_tag "booking[end_at]", @booking.end_at&.to_date %>

  <%# submit_tag %>
<%# end %>

<!-- <hr> -->

<!-- <h2>Form For</h2> -->

<% url_for(@booking) %>

<%= render "form" %>

7/2-tuesday-26/tour/app/views/bookings/index.html.erb
<h1>Bookings</h1>
<a href="/bookings/new">MAKE A BOOKING JEEZ</a>
<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Destination</th>
      <th>Start</th>
      <th>End</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.customer_name %></td>
        <td><%= booking.destination %></td>
        <td><%= booking.start_at %></td>
        <td><%= booking.end_at %></td>
        <td>
          <%= link_to "Edit", edit_booking_path(booking) %>
          <!-- <a href="/bookings/<%= booking.id %>/edit">Edit</a> -->

          <%= link_to "Delete", "/bookings/#{booking.id}", method: 'delete' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

7/2-tuesday-26/tour/app/views/bookings/new.html.erb
<!-- <form class="" action="/bookings" method="post">
  <label for="">Customer Name</label>
  <input type="text" name="booking[customer_name]" value="">

  <input type="submit" name="" value="Save">
</form> -->

<%= render "form" %>

7/2-tuesday-26/tour/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

7/2-tuesday-26/tour/app/views/welcome/homepage.html.erb
<h1>
  Robby's Travel Agency
</h1>

<%= link_to "Bookings", bookings_path %>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>